### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'c:\workspace\project\c:'

### ISSUE THREAD

**Issue by Zilarrezko** [noseglid/atom-build#76]
Looks like the error matching isn't working for me anymore, was it broken in an atom update?

1. build
2. spam go to error until you've gone to an error more times than there are errors

Looks like it's adding the project's path to the beginning of the filepath in error matching, not sure how to fix that.

{
  "cmd": "build.bat",
  "args": [],
  "sh": false,
  "cwd": "{PROJECT_PATH}",
  "env": {
  },
  "errorMatch": "(?<file>.+)\\((?<line>\\d+)\\)"
}

I tried making cwd to "" (nothing) and same thing. I'm pretty ignorant.

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.33.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'c:\workspace\project\c:'

```
At ATOM_SHELL_ASAR.js:50

Error: ENOENT: no such file or directory, lstat 'c:\workspace\project\c:'
    at Error (native)
    at fs.lstatSync (fs.js:836:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
    at Object.realpathSync (fs.js:1439:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:243:29)
    at Object.module.exports.replace (C:\Users\Jesse\.atom\packages\build\lib\build.js:138:27)
    at Object.module.exports.errorMatchGoTo (C:\Users\Jesse\.atom\packages\build\lib\build.js:171:30)
    at Object.module.exports.errorMatch (C:\Users\Jesse\.atom\packages\build\lib\build.js:190:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Jesse\AppData\Local\atom\app-0.199.0\resources\app.asar\src\command-registry.js:238:29)
    at C:\Users\Jesse\AppData\Local\atom\app-0.199.0\resources\app.asar\src\command-registry.js:3:61
```

### Commands

```
     -0:44.9.0 build:trigger (atom-text-editor.editor.is-focused)
     -0:43.5.0 build:error-match (atom-workspace.workspace.scrollbars-visible-always.theme-singularity-syntax.theme-one-dark-ui)
     -0:16.6.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:15.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:11.5.0 build:trigger (atom-text-editor.editor.is-focused)
  3x -0:05.4.0 build:error-match (atom-workspace.workspace.scrollbars-visible-always.theme-singularity-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "background-tips",
      "autocomplete-plus"
    ],
    "projectHome": "Z:\\github",
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "singularity-syntax"
    ]
  },
  "build": {
    "saveOnBuild": true,
    "minimizedHeight": 0.1
  }
}
```

### Installed Packages

```coffee
# User
build, v0.33.0
color-picker, v1.7.0
emacs-flow, v0.1.0
file-icons, v1.5.5
highlight-selected, v0.9.3
singularity-syntax, v0.1.0

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Thanks for reporting. Could you provide a sample output of what you're trying to match as well?

**Comment by Zilarrezko** [comment]
Example:

Executing: build.bat 
src.cpp
c:\workspace\school\cs_260\sorting\src\src.cpp(316): error C2065: 'PCFreq': undeclared identifier
c:\workspace\school\cs_260\sorting\src\src.cpp(317): error C2065: 'PCFreq': undeclared identifier
c:\workspace\school\cs_260\sorting\src\src.cpp(318): error C2065: 'PCFreq': undeclared identifier

End Example.

Interesting though... How the error match in the OP is missing things in pointed brackets. Are things in angled brackets not displayed?

"errorMatch": "(?\<file\>.+)\\\\((?\<line\>\\\\d+)\\\\)"

I guess I had to use an escape character before those angled brackets. That is the exact errorMatch in my .atom-build

**Comment by noseglid** [comment]
I found some issues when it didn't find the matched file. I've pushed a fix for this on master. Would you mind testing it see if it solves the issue for you? I can not reproduce with the output you've given me so it might be an issue with other environments (I am currently on Ubuntu Linux).

**Comment by Zilarrezko** [comment]
Throwing this error while finding this error (I just wanted to say that).

Matched file does not exist: c:\workspace\project\c:\workspace\project\src\win32.cpp

That's the whole line.

**Comment by noseglid** [comment]
I see that your paths are absolute, which seems to be the likely cause of this error (introduced in https://github.com/noseglid/atom-build/commit/0314b1d33b1d5ba6a00a1193c5fcda15f32bad85)

I've just merged a PR which allows you to tell `build` that the matched file really is absolute (https://github.com/noseglid/atom-build/commit/d2a0aaa1133506a853549ed6e61c30b8a8c7f86d). Please try with latest from master, and change your `errorMatch` names from `(?<file> ...` to `(?<absFile> ...`.

**Comment by Zilarrezko** [comment]
When trying to goto error.

![screenhunter_09 may 18 02 50](https://cloud.githubusercontent.com/assets/8561784/7678417/bc1124b8-fd08-11e4-9c97-0ccdc1683fea.jpg)

**Comment by noseglid** [comment]
Thats weird. Can you get a stack trace for that?

**Comment by Zilarrezko** [comment]
When I clicked on index.js:52. It brings up a source file, highlighting the same line that is highlighted here:

![screenhunter_10 may 18 03 07](https://cloud.githubusercontent.com/assets/8561784/7678719/336d767c-fd0b-11e4-81b9-0e9f970eeb71.jpg)

Clicking on fs.js:207 does nothing. (I may just be an idiot and not know where the call stack is, I'll keep looking).

**Comment by noseglid** [comment]
Hmm, I copied your atom-build file and executed a command which gives that exact same output as you said, and it gives the correct error matching.

How did you install atom-build from master?
This is what I would recommend

```
git clone https://github.com/noseglid/atom-build
cd atom-build
apm install
apm link
```

then restart Atom

**Comment by Zilarrezko** [comment]
Alright here we are...

[Enter steps to reproduce below:]

1. build
2. goto error

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.33.0


### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:207

TypeError: path must be a string
    at TypeError (native)
    at fs.exists (fs.js:207:11)
    at Object.fs.exists (ATOM_SHELL_ASAR.js:286:16)
    at Object.module.exports.errorMatchGoTo (Z:\github\atom-build\lib\build.js:178:8)
    at Object.module.exports.errorMatch (Z:\github\atom-build\lib\build.js:206:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Jesse\AppData\Local\atom\app-0.199.0\resources\app.asar\src\command-registry.js:238:29)
    at C:\Users\Jesse\AppData\Local\atom\app-0.199.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Jesse\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Jesse\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Jesse\AppData\Local\atom\app-0.199.0\resources\app.asar\src\window-event-handler.js:178:20)
```

### Commands

```
     -0:06.4.0 build:trigger (atom-text-editor.editor.is-focused)
     -0:04.4.0 build:error-match (atom-workspace.workspace.scrollbars-visible-always.theme-singularity-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "background-tips",
      "autocomplete-plus"
    ],
    "projectHome": "Z:\\github",
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "singularity-syntax"
    ]
  },
  "build": {
    "saveOnBuild": true,
    "minimizedHeight": 0.1
  }
}
```

### Installed Packages

```coffee
# User
build, v0.33.0
color-picker, v1.7.0
emacs-flow, v0.1.0
file-icons, v1.5.5
highlight-selected, v0.9.3
singularity-syntax, v0.1.0

# Dev
build, v0.33.0
```

**Comment by noseglid** [comment]
Okay. I'd be willing to bet your regular expression didn't match any file. Did get the latest from master (e.g. can you verify that the latest git-commit is `672a31b`)?

Also, did you change the name of the regular expression to `absFile`, case is important!

It is, however, a bug that you get this error. It really should check that it really matches a file before attempting to use it.

**Comment by Zilarrezko** [comment]
Okay great! 

I forgot to capitalize File in absFile in the errorMatch. It's working now, going from line to line. Thanks man.

**Comment by noseglid** [comment]
Excellent! Glad to hear. You also helped sniff out an issue if anyway makes that mistake (and trust me, you're not going to be the last). I'll add a fix for that! Thanks for taking the time to help me troubleshoot this!
