### ISSUE TITLE
Installation is hanging.

### ISSUE THREAD

**Issue by stibinator** [noseglid/atom-build#569]
If I use `apm install build` the installation hangs. I'm on Windows10, through a network proxy (which apm is configured to use, it works fine with other packages, so I don't think it's the problem). Here's the log:

https://gist.github.com/stibinator/8c970ed989b704153299190a1fb3e3d0

**Comment by sepiatonal** [comment]
I'm experiencing the same problem, on Windows 7.

**Comment by mienaikoe** [comment]
experiencing the same problem on OSX

**Comment by cs50AdverD** [comment]
Same problem on Windows 10 Pro.

**Comment by AlexHalbleib** [comment]
Same problem here on Windows 7.

**Comment by noseglid** [comment]
I don't really have time to investigate at the moment, and this seems really urgent. Anyone willing to dig into what the root cause might be?

**Comment by mathompl** [comment]
damn, I've reinstalled platform.io due to console not working, and now I cant install it again :( (hangs on installing build)

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide/issues/2059#issuecomment-415584717

>  seems to hang on getmac -> editions dependencies install

@noseglid could you remove/disable google analytics and dependency to https://github.com/noseglid/atom-build/blob/master/lib/google-analytics.js#L17 ? Please make a next hotfix release.

P.S: PlatformIO Users, please switch to [PlatformIO IDE for VSCode](https://platformio.org/install/ide?install=vscode)

We will discontinue Atom package soon.

**Comment by ynhhoJ** [comment]
@noseglid How we can use 69.0 version?
I tried to install manually, but it doesn't work...

**Comment by noseglid** [comment]
I have no idea what the root cause is. If it doesn't work with 0.69.0 either I guess that doesn't solve it...

**Comment by ynhhoJ** [comment]
```
rror: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/lJohh/AppData/Local/atom/app-1.30.0/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\native-compile-cache.js:66:33)
    at Object.activate (file:///C:/Users/lJohh/.atom/packages/build/lib/build.js:16:5)
    at Package.activateNow (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:230:33)
    at measure (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:206:33)
    at Package.measure (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:88:25)
    at activationPromise.Promise (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:198:38)
    at PackageManager.activatePackage (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package-manager.js:695:42)
    at config.transactAsync (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package-manager.js:670:36)
    at Config.transactAsync (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\config.js:866:28)
    at PackageManager.activatePackages (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package-manager.js:668:23)
    at PackageManager.activate (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\package-manager.js:647:50)
    at loadStatePromise.loadState.then (C:\Users\lJohh\AppData\Local\atom\app-1.30.0\resources\app\src\atom-environment.js:875:27)
```
This is on 69.0 (manual installation) error.

**Comment by ynhhoJ** [comment]
@noseglid , i think, if you can delete temporarily 0.70.0 release, we can try to install an 0.69.0 release...

**Comment by jloow** [comment]
When I tried to install it using `apm install build --verbose`, it got stuck at installing `REQUEST emitting complete https://registry.npmjs.org/sprintf-js`.

However, installing an older version using `apm install build@0.69.0` worked.

**Comment by ynhhoJ** [comment]
@jloow , thank you, it's work for me!

**Comment by NewcDukem** [comment]
> When I tried to install it using `apm install build --verbose`, it got stuck at installing `REQUEST emitting complete https://registry.npmjs.org/sprintf-js`.
> 
> However, installing an older version using `apm install build@0.69.0` worked.

Started having this problem today after the Atom 1.39 update. I've tried using `apm install build@0.69.0 `but I'm still hung up on "Atom Dependencies". Is there a step I'm missing?

**Comment by Rixtyan** [comment]
This fucking problem is still here.... Atom 1.53, win7, platformio, python3.8

I.. just want to build a little esp firmware, instead of it i spend around a week to try install broken software

**Comment by FranklinBerger** [comment]
> P.S: PlatformIO Users, please switch to PlatformIO IDE for VSCode
We will discontinue Atom package soon.

Ok, but is there a possibility to stop the instalation without unintalling atom?
