### ISSUE TITLE
emitter.prependListener is not a function

### ISSUE THREAD

**Issue by borshua** [noseglid/atom-build#485]
Hi.
I launched build by F9 key today, and saw this error **emitter.prependListener is not a function**.
I have already reinstalled package, but error doesn't fixed.

What can i do?

**Comment by Jordyderuijter** [comment]
Also happened to me since the Atom 1.12.0 update. Build run only starts once and can't be run again after until I restart Atom.

**Comment by ivankravets** [comment]
Fixed in https://github.com/noseglid/atom-build/commit/dbc8b84a746b069b2e1a5d1e32c2f0a50f31d806

@noseglid could you release new version becaue "build" has stopped work with new Atom 1.12? Thanks!

**Comment by Jordyderuijter** [comment]
Edited the file locally now until the new version is released. It works, thanks. :)

**Comment by noseglid** [comment]
It's been released now!
